"""Generate the customer fixture that seeds the database.

Written as a script rather than hand-edited JSON so credentials stay unique
and the roster stays reproducible.

    python make_customers.py            # rewrite data/customers_seed.json
    python make_customers.py --check    # verify the existing file, change nothing

Deterministic: a fixed seed, so the same credentials come out every run.

Segment and name are synthetic-but-plausible; the 4 segments themselves and
the 1-1 segment-to-card mapping are the client's real answer (see
data/products.json / data/segments.md), not invented. `stated_interests` is
left empty for half the roster on purpose - Scenario 2/3 needs a customer who
has NOT already told the bot what they care about, to demonstrate the
one-question slot-fill in app/flows.py rather than always having the answer
pre-loaded.
"""

from __future__ import annotations

import sys

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

import json
import random
from pathlib import Path

OUT_PATH = Path(__file__).resolve().parent / "data" / "customers_seed.json"
SEED = 20260805

# (name, segment, age, stated_interests) - segment alone determines the card
# (app/rules_engine.py::card_for_segment), so there is no income/product
# threshold to model here the way there was for the earlier synthetic
# catalogue.
PEOPLE = [
    ("Nguyen Van An",  "MASS",          34, ["mua sắm online"]),
    ("Tran Thi Bich",  "MASS",          29, []),
    ("Le Minh Chau",   "MASS_AFFLUENT", 38, ["ăn uống", "giải trí"]),
    ("Pham Quoc Dung", "MASS_AFFLUENT", 41, []),
    ("Hoang Thi Ha",   "AFFLUENT",      36, ["du lịch"]),
    ("Vu Duc Hieu",    "AFFLUENT",      45, []),
    ("Dang Thi Lan",   "PRIVATE",       50, ["golf", "du lịch nước ngoài"]),
    ("Bui Van Long",   "PRIVATE",       47, []),
]


def build() -> dict:
    rng = random.Random(SEED)
    used_credentials: set[tuple[str, str]] = set()
    customers = []

    for index, (name, segment, age, interests) in enumerate(PEOPLE):
        customer_id = f"CUS-{100301 + index * 7}"

        # Unique pair, checked rather than assumed - two customers sharing a
        # phone/ID pair would make verification ambiguous.
        while True:
            phone = f"{rng.randint(1000, 9999)}"
            national = f"{rng.randint(1000, 9999)}"
            if (phone, national) not in used_credentials:
                used_credentials.add((phone, national))
                break

        customers.append({
            "customer_id": customer_id,
            "name": name,
            "given_name": name.split()[-1],
            "phone_last4": phone,
            "national_id_last4": national,
            "segment": segment,
            "age": age,
            "stated_interests": interests,
        })

    return {"customers": customers}


def render_comment(customers: list[dict]) -> list[str]:
    lines = [
        "Synthetic customer roster - names/ages/credentials are invented, but",
        "the 4 segments and their 1-1 mapping to a card are the client's real",
        "answer. Deterministic, regenerated by make_customers.py. Auth codes:",
        "last 4 of phone + last 4 of national ID, not shown on screen, kept",
        "here for whoever is running the demo.",
        "",
    ]
    for c in customers:
        lines.append(f"  {c['name']:<18} {c['phone_last4']} {c['national_id_last4']}   {c['segment']}")
    return lines


def main() -> int:
    check_only = "--check" in sys.argv
    data = build()
    data = {"_comment": render_comment(data["customers"]), **data}
    rendered = json.dumps(data, indent=2, ensure_ascii=False) + "\n"

    if check_only:
        if not OUT_PATH.exists():
            print(f"{OUT_PATH} does not exist - run without --check first.")
            return 1
        current = OUT_PATH.read_text(encoding="utf-8")
        if current == rendered:
            print(f"{OUT_PATH} matches the generator output ({len(data['customers'])} customers).")
            return 0
        print(f"{OUT_PATH} is out of date - run without --check to regenerate.")
        return 1

    OUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"Wrote {OUT_PATH} ({len(data['customers'])} customers).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
